### ISSUE TITLE
Essentia Import bus crash (Ticking GridNode) in v2.3.0

### ISSUE THREAD

**Issue by Nivid-IT** [Delfayne/ThaumicEnergistics#40]
**Describe the bug**
Bug described in #32 is back in version 2.3.0 and I can confirm it is indeed related to (partially) unloaded chunks as was suspected.

Connecting an ME Essentia Import Bus to an Advanced Alchemical Furnace immediately crashes my server due to "Ticking GridNode"

```
Description: Ticking GridNode

java.lang.NullPointerException: Ticking GridNode
    at thaumicenergistics.part.PartEssentiaImportBus.doWork(PartEssentiaImportBus.java:74)
    at thaumicenergistics.part.PartSharedEssentiaBus.tickingRequest(PartSharedEssentiaBus.java:162)
    at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:91)
    at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:40)
    at appeng.me.Grid.update(Grid.java:229)
    at appeng.hooks.TickHandler.onTick(TickHandler.java:196)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2226_TickHandler_onTick_TickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1256)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:1206)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1817)
    at java.lang.Thread.run(Thread.java:748)
```
    
```
-- PartEssentiaImportBus being ticked. --
  CurrentTickRate: 22
  MinTickRate: 5
  MaxTickRate: 40
  MachineType: thaumicenergistics.part.PartEssentiaImportBus
  GridBlockType: thaumicenergistics.integration.appeng.grid.ThEGridBlock
  ConnectedSides: [INTERNAL]
  Location: dimension=0, x=-11380, y=25, z=20097
  ```

**Version Information**
 - Minecraft: 1.12.2
 - Forge: 1.12.214.23.5.2860
 - Applied Energistics: v0.56.5
 - Thaumcraft: 1.12.2-6.1.BETA26
 - Thaumic Energistics: 2.3.0
 - Modpack: The 1.12.2 Pack version 1.6.0
 - SpongeForge 1.12.2-2838-7.4.8-RC0
 - mixinbooter-9.1

**Comment by Delfayne** [comment]
Unfortunate, I'll try to look at it

**Comment by Delfayne** [comment]
I have added further null checking, please try https://github.com/Delfayne/ThaumicEnergistics/releases/tag/v2.3.1 and let me know if that fixes your problem.

**Comment by Delfayne** [comment]
I'm closing this as "probably fixed". Let me know later if that's not the case
