### ISSUE TITLE
Essentia Export bus crash (Ticking GridNode) 

### ISSUE THREAD

**Issue by Nivid-IT** [Delfayne/ThaumicEnergistics#62]
**Describe the bug**

Connecting an ME Essentia Import Bus to a Primordial Accretion Chamber from Thaumic Wonders immediately crashes my server due to "Ticking GridNode". **This is a similar bug to the one I previously reported here: https://github.com/Delfayne/ThaumicEnergistics/issues/28**

**Screenshots**
![2024-12-12_13 21 06](https://github.com/user-attachments/assets/8efe7c9e-a5dc-4170-b6cd-59e4e9168fa9)

**Version Information with which the crash DOES TAKE PLACE**
- Minecraft: 1.12.2
- Forge: 1.12.214.23.5.2860
- Applied Energistics: 0.56-7c6ceef
- Thaumcraft: 1.12.2-6.1.BETA26
- Thaumic Energistics: 2.3.3
- Thaumic Tinkerer: 1.12.2-5.7.1
- Thaumic Wonders: 1.8.4-patched
- ThaumcraftFix-1.12.2-1.0.7.jar
- Modpack: The 1.12.2 Pack version 1.6.4
- SpongeForge 1.12.2-2838-7.4.8-RC4142
- mixinbooter-9.4

**Version Information with which the crash does NOT TAKE PLACE**
- Minecraft: 1.12.2
- Forge: 1.12.214.23.5.2860
- Applied Energistics: 0.56-7c6ceef
- Thaumcraft: 1.12.2-6.1.BETA26
- Thaumic Tinkerer: 1.12.2-5.4.2
- Thaumic Energistics: 2.3.3
- Thaumic Wonders: 1.8.4
- thaumicfixes-1.0-nolibs.jar
- Modpack: The 1.12.2 Pack version 1.6.3
- SpongeForge 1.12.2-2838-7.4.8-RC4142
- mixinbooter-9.1

**Additional context**
Not Required. Add any other context about the problem here.

**Logs/Crashlogs**
```---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Why did you do that?

Time: 2024-12-10 20:09:04 UTC
Description: Ticking GridNode

java.lang.NullPointerException: Ticking GridNode
    at net.minecraft.world.chunk.BlockStateContainer.handler$bee000$totalOverride(BlockStateContainer.java:2027)
    at net.minecraft.world.chunk.BlockStateContainer.set(BlockStateContainer.java)
    at net.minecraft.world.chunk.BlockStateContainer.handler$bmf000$reid$newSetDataFromNBT(BlockStateContainer.java:2610)
    at net.minecraft.world.chunk.BlockStateContainer.setDataFromNBT(BlockStateContainer.java)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.readChunkFromNBT(AnvilChunkLoader.java:452)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:129)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:93)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89)
    at net.minecraft.world.gen.ChunkProviderServer.redirect$zmj000$impl$ProvideChunkForced(ChunkProviderServer.java:1644)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135)
    at net.minecraft.world.World.getChunk(World.java:310)
    at net.minecraft.world.World.getChunk(World.java:305)
    at net.minecraft.world.World.getTileEntity(World.java:2402)
    at com.verdantartifice.thaumicwonders.common.tiles.misc.TilePrimordialAccretionChamberPlaceholder.findCentralChamber(TilePrimordialAccretionChamberPlaceholder.java:75)
    at com.verdantartifice.thaumicwonders.common.tiles.misc.TilePrimordialAccretionChamberPlaceholder.doesContainerAccept(TilePrimordialAccretionChamberPlaceholder.java:122)
    at thaumicenergistics.part.PartEssentiaExportBus.doWork(PartEssentiaExportBus.java:88)
    at thaumicenergistics.part.PartSharedEssentiaBus.tickingRequest(PartSharedEssentiaBus.java:162)
    at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:91)
    at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:40)
    at appeng.me.Grid.update(Grid.java:229)
    at appeng.hooks.TickHandler.onTick(TickHandler.java:196)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2285_TickHandler_onTick_TickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1256)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:1206)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1817)
    at java.lang.Thread.run(Thread.java:748)

No Mixin Metadata is found in the Stacktrace.


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- PartEssentiaExportBus being ticked. --
  CurrentTickRate: 32
  MinTickRate: 5
  MaxTickRate: 60
  MachineType: thaumicenergistics.part.PartEssentiaExportBus
  GridBlockType: thaumicenergistics.integration.appeng.grid.ThEGridBlock
  ConnectedSides: [INTERNAL]
  Location: dimension=0, x=-16736, y=75, z=7531
```

**Comment by Delfayne** [comment]
Again, can't reproduce this, but there's some definite sus over how the export bus checks were being done. For instance, the connected TE is accessed three times, where it could have become null after the first time.

I've reduced these checks down and split them up to help for debugging later.
